import Foundation

/// Errors thrown by the libssh2 wrapper layer.
public enum LibSSH2Error: Error, Equatable, CustomStringConvertible {
    case socketNone(String?)
    case bannerReceive(String?)
    case bannerSend(String?)
    case invalidMAC(String?)
    case keyExchangeFailure(String?)
    case allocationFailure(String?)
    case socketSend(String?)
    case timeout(String?)
    case hostKeyInitialization(String?)
    case hostKeySigning(String?)
    case decrypt(String?)
    case socketDisconnect(String?)
    case protocolError(String?)
    case passwordExpired(String?)
    case file(String?)
    case methodNone(String?)
    case authenticationFailed(String?)
    case publicKeyUnverified(String?)
    case channelOutOfOrder(String?)
    case channelFailure(String?)
    case channelRequestDenied(String?)
    case channelUnknown(String?)
    case channelWindowExceeded(String?)
    case channelPacketExceeded(String?)
    case channelClosed(String?)
    case channelEOFSent(String?)
    case scpProtocol(String?)
    case zlib(String?)
    case socketTimeout(String?)
    case sftpProtocol(String?)
    case requestDenied(String?)
    case methodNotSupported(String?)
    case invalidArgument(String?)
    case invalidPollType(String?)
    case publicKeyProtocol(String?)
    case wouldBlock(String?)
    case bufferTooSmall(String?)
    case badUse(String?)
    case compress(String?)
    case outOfBoundary(String?)
    case agentProtocol(String?)
    case socketReceive(String?)
    case encrypt(String?)
    case badSocket(String?)
    case knownHosts(String?)
    case channelWindowFull(String?)
    case keyFileAuthFailed(String?)
    case randomGenerator(String?)
    case missingUserAuthBanner(String?)
    case algorithmUnsupported(String?)
    case macFailure(String?)
    case hashInitialization(String?)
    case hashCalculation(String?)
    case storeOverflow(String?)
    case nullPointer(function: String)
    case sftp(statusCode: UInt)
    case unknown(code: Int32, message: String?)

    public var description: String {
        switch self {
        case let .socketNone(message): Self.describe("socket none", message)
        case let .bannerReceive(message): Self.describe("banner receive", message)
        case let .bannerSend(message): Self.describe("banner send", message)
        case let .invalidMAC(message): Self.describe("invalid MAC", message)
        case let .keyExchangeFailure(message): Self.describe("key exchange failure", message)
        case let .allocationFailure(message): Self.describe("allocation failure", message)
        case let .socketSend(message): Self.describe("socket send", message)
        case let .timeout(message): Self.describe("timeout", message)
        case let .hostKeyInitialization(message): Self.describe("host key initialization", message)
        case let .hostKeySigning(message): Self.describe("host key signing", message)
        case let .decrypt(message): Self.describe("decrypt", message)
        case let .socketDisconnect(message): Self.describe("socket disconnect", message)
        case let .protocolError(message): Self.describe("protocol error", message)
        case let .passwordExpired(message): Self.describe("password expired", message)
        case let .file(message): Self.describe("file", message)
        case let .methodNone(message): Self.describe("method none", message)
        case let .authenticationFailed(message): Self.describe("authentication failed", message)
        case let .publicKeyUnverified(message): Self.describe("public key unverified", message)
        case let .channelOutOfOrder(message): Self.describe("channel out of order", message)
        case let .channelFailure(message): Self.describe("channel failure", message)
        case let .channelRequestDenied(message): Self.describe("channel request denied", message)
        case let .channelUnknown(message): Self.describe("channel unknown", message)
        case let .channelWindowExceeded(message): Self.describe("channel window exceeded", message)
        case let .channelPacketExceeded(message): Self.describe("channel packet exceeded", message)
        case let .channelClosed(message): Self.describe("channel closed", message)
        case let .channelEOFSent(message): Self.describe("channel EOF sent", message)
        case let .scpProtocol(message): Self.describe("SCP protocol", message)
        case let .zlib(message): Self.describe("zlib", message)
        case let .socketTimeout(message): Self.describe("socket timeout", message)
        case let .sftpProtocol(message): Self.describe("SFTP protocol", message)
        case let .requestDenied(message): Self.describe("request denied", message)
        case let .methodNotSupported(message): Self.describe("method not supported", message)
        case let .invalidArgument(message): Self.describe("invalid argument", message)
        case let .invalidPollType(message): Self.describe("invalid poll type", message)
        case let .publicKeyProtocol(message): Self.describe("public key protocol", message)
        case let .wouldBlock(message): Self.describe("would block", message)
        case let .bufferTooSmall(message): Self.describe("buffer too small", message)
        case let .badUse(message): Self.describe("bad use", message)
        case let .compress(message): Self.describe("compress", message)
        case let .outOfBoundary(message): Self.describe("out of boundary", message)
        case let .agentProtocol(message): Self.describe("agent protocol", message)
        case let .socketReceive(message): Self.describe("socket receive", message)
        case let .encrypt(message): Self.describe("encrypt", message)
        case let .badSocket(message): Self.describe("bad socket", message)
        case let .knownHosts(message): Self.describe("known hosts", message)
        case let .channelWindowFull(message): Self.describe("channel window full", message)
        case let .keyFileAuthFailed(message): Self.describe("key file auth failed", message)
        case let .randomGenerator(message): Self.describe("random generator", message)
        case let .missingUserAuthBanner(message): Self.describe("missing userauth banner", message)
        case let .algorithmUnsupported(message): Self.describe("algorithm unsupported", message)
        case let .macFailure(message): Self.describe("MAC failure", message)
        case let .hashInitialization(message): Self.describe("hash initialization", message)
        case let .hashCalculation(message): Self.describe("hash calculation", message)
        case let .storeOverflow(message): Self.describe("store overflow", message)
        case let .nullPointer(function): "\(function) returned NULL"
        case let .sftp(statusCode): "SFTP status code \(statusCode)"
        case let .unknown(code, message): Self.describe("libssh2 error \(code)", message)
        }
    }

    public init(code: Int32, message: String? = nil) {
        switch code {
        case -1: self = .socketNone(message)
        case -2: self = .bannerReceive(message)
        case -3: self = .bannerSend(message)
        case -4: self = .invalidMAC(message)
        case -5, -8: self = .keyExchangeFailure(message)
        case -6: self = .allocationFailure(message)
        case -7: self = .socketSend(message)
        case -9: self = .timeout(message)
        case -10: self = .hostKeyInitialization(message)
        case -11: self = .hostKeySigning(message)
        case -12: self = .decrypt(message)
        case -13: self = .socketDisconnect(message)
        case -14: self = .protocolError(message)
        case -15: self = .passwordExpired(message)
        case -16: self = .file(message)
        case -17: self = .methodNone(message)
        case -18: self = .authenticationFailed(message)
        case -19: self = .publicKeyUnverified(message)
        case -20: self = .channelOutOfOrder(message)
        case -21: self = .channelFailure(message)
        case -22: self = .channelRequestDenied(message)
        case -23: self = .channelUnknown(message)
        case -24: self = .channelWindowExceeded(message)
        case -25: self = .channelPacketExceeded(message)
        case -26: self = .channelClosed(message)
        case -27: self = .channelEOFSent(message)
        case -28: self = .scpProtocol(message)
        case -29: self = .zlib(message)
        case -30: self = .socketTimeout(message)
        case -31: self = .sftpProtocol(message)
        case -32: self = .requestDenied(message)
        case -33: self = .methodNotSupported(message)
        case -34: self = .invalidArgument(message)
        case -35: self = .invalidPollType(message)
        case -36: self = .publicKeyProtocol(message)
        case -37: self = .wouldBlock(message)
        case -38: self = .bufferTooSmall(message)
        case -39: self = .badUse(message)
        case -40: self = .compress(message)
        case -41: self = .outOfBoundary(message)
        case -42: self = .agentProtocol(message)
        case -43: self = .socketReceive(message)
        case -44: self = .encrypt(message)
        case -45: self = .badSocket(message)
        case -46: self = .knownHosts(message)
        case -47: self = .channelWindowFull(message)
        case -48: self = .keyFileAuthFailed(message)
        case -49: self = .randomGenerator(message)
        case -50: self = .missingUserAuthBanner(message)
        case -51: self = .algorithmUnsupported(message)
        case -52: self = .macFailure(message)
        case -53: self = .hashInitialization(message)
        case -54: self = .hashCalculation(message)
        case -55: self = .storeOverflow(message)
        default: self = .unknown(code: code, message: message)
        }
    }

    private static func describe(_ name: String, _ message: String?) -> String {
        guard let message, !message.isEmpty else { return name }
        return "\(name): \(message)"
    }
}
