#!/usr/bin/env python3
"""Qualify libssh2's Apple OpenSSL includes without editing the submodule."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "vendor/libssh2/src/openssl.h"
OUTPUT = ROOT / "Sources/libssh2/apple/openssl_backend.h"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed adapter is stale")
    args = parser.parse_args()
    original = SOURCE.read_text()
    if "#ifndef LIBSSH2_OPENSSL_H" not in original:
        raise SystemExit("The pinned libssh2 OpenSSL include guard changed; review the Apple adapter")
    adapted, count = re.subn(
        r"(#\s*include\s*)<openssl/([^>]+)>",
        r"\1<OpenSSLCrypto/swiftsftp_openssl/\2>", original
    )
    if not count:
        raise SystemExit("No OpenSSL includes found in the pinned libssh2 backend")
    expected = (
        "/* Generated by Scripts/generate-libssh2-apple-backend.py. Do not edit.\n"
        " * Only OpenSSL include paths differ from vendor/libssh2/src/openssl.h.\n"
        " * Loaded through HAVE_CONFIG_H before libssh2 selects its crypto backend.\n"
        " */\n" + adapted
    )
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != expected:
            raise SystemExit("Stale Apple backend: run python3 Scripts/generate-libssh2-apple-backend.py")
        print(f"PASS: Apple backend matches libssh2, with {count} qualified includes")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)
        print(f"Generated Apple backend with {count} qualified includes")


if __name__ == "__main__":
    main()
