import Foundation

let tempDir = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

func read(_ name: String) -> String {
    let url = URL(fileURLWithPath: tempDir).appendingPathComponent(name)
    return ((try? String(contentsOf: url, encoding: .utf8)) ?? "")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

struct KeyType {
    let name: String
    let shorthandFile: String
}

let keyTypes = [
    KeyType(name: "RSA", shorthandFile: "rsa_shorthand"),
    KeyType(name: "P256", shorthandFile: "p256_shorthand"),
    KeyType(name: "P384", shorthandFile: "p384_shorthand"),
    KeyType(name: "P521", shorthandFile: "p521_shorthand"),
    KeyType(name: "Ed25519", shorthandFile: "ed25519_shorthand"),
]

var lines: [String] = []
lines.append("// Generated by generate-hostkey-test-data.sh — DO NOT EDIT")
lines.append("")
lines.append("enum HostkeyValidationTestData {")
lines.append("    static let testHost = \"127.0.0.1\"")
lines.append("    static let portHost = \"[example.com]:2222\"")
lines.append("    static let comment = \"my-server\"")
lines.append("    static let hashedLine = \(read("hashed_line").debugDescription)")
lines.append("")

for (index, keyType) in keyTypes.enumerated() {
    let shorthand = read(keyType.shorthandFile)
    lines.append("    enum \(keyType.name) {")
    lines.append("        static let shorthand = \(shorthand.debugDescription)")
    lines.append("        static let fullLine = \"\\(HostkeyValidationTestData.testHost) \\(shorthand)\"")
    lines.append(
        "        static let portLine = \"\\(HostkeyValidationTestData.portHost) \\(shorthand)\""
    )
    lines.append(
        "        static let lineWithComment = \"\\(HostkeyValidationTestData.testHost) \\(shorthand) \\(HostkeyValidationTestData.comment)\""
    )
    lines.append("    }")
    if index < keyTypes.count - 1 {
        lines.append("")
    }
}

lines.append("}")
lines.append("")

try lines.joined(separator: "\n").write(toFile: outputPath, atomically: true, encoding: .utf8)
