import Foundation

let tempDir = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]
let testPassword = CommandLine.arguments[3]

func read(_ name: String) -> String {
    let url = URL(fileURLWithPath: tempDir).appendingPathComponent(name)
    return ((try? String(contentsOf: url, encoding: .utf8)) ?? "")
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

var lines: [String] = []

lines.append("// Generated by generate-key-test-data.sh — DO NOT EDIT")
lines.append("")
lines.append("enum KeyValidationTestData {")
lines.append("    static let testPassword = \(testPassword.debugDescription)")
lines.append("")

struct KeyType {
    let name: String
    let privateFile: String
    let encryptedFile: String
    let publicFile: String
    let traditionalFile: String?
    let openSSHFile: String?
}

let keyTypes = [
    KeyType(name: "RSA", privateFile: "rsa_private.pem", encryptedFile: "rsa_encrypted.pem", publicFile: "rsa_public.pem", traditionalFile: "rsa_traditional.pem", openSSHFile: "openssh_rsa"),
    KeyType(name: "P256", privateFile: "p256_private.pem", encryptedFile: "p256_encrypted.pem", publicFile: "p256_public.pem", traditionalFile: "p256_traditional.pem", openSSHFile: "openssh_p256"),
    KeyType(name: "P384", privateFile: "p384_private.pem", encryptedFile: "p384_encrypted.pem", publicFile: "p384_public.pem", traditionalFile: "p384_traditional.pem", openSSHFile: "openssh_p384"),
    KeyType(name: "P521", privateFile: "p521_private.pem", encryptedFile: "p521_encrypted.pem", publicFile: "p521_public.pem", traditionalFile: "p521_traditional.pem", openSSHFile: "openssh_p521"),
    KeyType(name: "Curve25519", privateFile: "ed25519_private.pem", encryptedFile: "ed25519_encrypted.pem", publicFile: "ed25519_public.pem", traditionalFile: nil, openSSHFile: "openssh_ed25519"),
]

for (i, kt) in keyTypes.enumerated() {
    lines.append("    enum \(kt.name) {")
    lines.append("        static let privateKey = \(read(kt.privateFile).debugDescription)")
    lines.append("        static let encryptedPrivateKey = \(read(kt.encryptedFile).debugDescription)")
    lines.append("        static let publicKey = \(read(kt.publicFile).debugDescription)")
    if let traditionalFile = kt.traditionalFile {
        lines.append("        static let traditionalPrivateKey = \(read(traditionalFile).debugDescription)")
    }
    if let openSSHFile = kt.openSSHFile {
        lines.append("        static let openSSHPrivateKey = \(read(openSSHFile).debugDescription)")
    }
    lines.append("    }")
    if i < keyTypes.count - 1 { lines.append("") }
}

lines.append("}")
lines.append("")

try lines.joined(separator: "\n").write(toFile: outputPath, atomically: true, encoding: .utf8)
